name: firebase_tools
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0


# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  firedart: ^0.9.7
  hive: ^2.2.3


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
